main = ".open-next/worker.js"
name = "on-page-router1"
 
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
 
# The binding name must be "ASSETS" when the cache is enabled
assets = { directory = ".open-next/assets", binding = "ASSETS" }

routes = [
  { pattern = "on-router.mahabubsany.com", custom_domain = true }
]